### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by p3t** [colinramsay/st2-bettertextarea#2]
Hello,
I would like to use your component in an commercial product - if possible.
Can you please specify a license for your source-code?

Thanks a lot
Peter

**Comment by colinramsay** [comment]
What license would you like? I have no problem with this being used in whatever way you like.

**Comment by p3t** [comment]
Hello,
I would recommend either 
- the Apache 2 license (http://www.apache.org/licenses/LICENSE-2.0.html) which widely used in the open source world and liberal enough to use the the software in commercial products.
- or the BSD license (http://www.linfo.org/bsdlicense.html) which is even more liberal

Thanks & best regards
Peter

**Comment by colinramsay** [comment]
If you supply a pull request I'd be happy to apply it.
